### ISSUE TITLE
States & LoadOrder, Circular Dependency and other BS

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#1048]
Tritt auf bei Konsolen-Commands.. z.b. cache:clear oder rails c

Circular Dep: 
Circular dependency detected while autoloading constant Organization::StateMachine (RuntimeError)

Kennt aasm nicht:
NoMethodError: undefined method `aasm' for #<Class:0x007fbebd2449f0>
/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/app/app/models/statistic_chart.rb:23:in `<class:StatisticChart>'
/app/app/models/statistic_chart.rb:5:in `<top (required)>'

**Comment by NilsVollmer** [comment]
Als Hotfix direkt umgesetzt & deployed.
