### ISSUE TITLE
Worker Probleme (eigentlich expired Angebote weiterhin approved)

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#521]
+ logischerweise auch keine Asana Tasks erzeugt.

**Comment by NilsVollmer** [comment]
Scheint ein generelles Problem mit den Workern zu sein - der regnerateHtmlWorker ist auch nicht durchgelaufen.

**Comment by NilsVollmer** [comment]
Log:
```console
2015-10-23T13:32:27.177760+00:00 heroku[worker.1]: State changed from crashed to starting
2015-10-23T13:32:46.057329+00:00 heroku[worker.1]: Starting process with command `bundle exec sidekiq`
2015-10-23T13:32:46.759634+00:00 heroku[worker.1]: State changed from starting to up
2015-10-23T13:32:51.064712+00:00 app[worker.1]: uninitialized constant Celluloid::SupervisionGroup
2015-10-23T13:32:51.064744+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidetiq-0.6.3/lib/sidetiq/supervisor.rb:2:in `<module:Sidetiq>'
2015-10-23T13:32:51.064746+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidetiq-0.6.3/lib/sidetiq/supervisor.rb:1:in `<top (required)>'
2015-10-23T13:32:51.064746+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidetiq-0.6.3/lib/sidetiq.rb:32:in `<top (required)>'
2015-10-23T13:32:51.064747+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/bundler/gems/clarat_base-9e7c5a8ce7ab/lib/clarat_base/engine.rb:15:in `<class:Engine>'
2015-10-23T13:32:51.064748+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/bundler/gems/clarat_base-9e7c5a8ce7ab/lib/clarat_base/engine.rb:2:in `<module:ClaratBase>'
2015-10-23T13:32:51.064749+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/bundler/gems/clarat_base-9e7c5a8ce7ab/lib/clarat_base/engine.rb:1:in `<top (required)>'
2015-10-23T13:32:51.064750+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/bundler/gems/clarat_base-9e7c5a8ce7ab/lib/clarat_base.rb:1:in `require'
2015-10-23T13:32:51.064751+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/bundler/gems/clarat_base-9e7c5a8ce7ab/lib/clarat_base.rb:1:in `<top (required)>'
2015-10-23T13:32:51.064751+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:76:in `require'
2015-10-23T13:32:51.064752+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
2015-10-23T13:32:51.064753+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:72:in `each'
2015-10-23T13:32:51.064753+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:72:in `block in require'
2015-10-23T13:32:51.064754+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in `each'
2015-10-23T13:32:51.064755+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in `require'
2015-10-23T13:32:51.064755+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler.rb:134:in `require'
2015-10-23T13:32:51.064756+00:00 app[worker.1]: /app/config/application.rb:5:in `<top (required)>'
2015-10-23T13:32:51.064756+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.5.1/lib/sidekiq/cli.rb:242:in `require'
2015-10-23T13:32:51.064757+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.5.1/lib/sidekiq/cli.rb:242:in `boot_system'
2015-10-23T13:32:51.064758+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.5.1/lib/sidekiq/cli.rb:50:in `run'
2015-10-23T13:32:51.064759+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.5.1/bin/sidekiq:13:in `<top (required)>'
2015-10-23T13:32:51.064759+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/bin/sidekiq:23:in `load'
2015-10-23T13:32:51.064760+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/bin/sidekiq:23:in `<main>'
2015-10-23T13:32:52.129718+00:00 heroku[worker.1]: Process exited with status 1
2015-10-23T13:32:52.139882+00:00 heroku[worker.1]: State changed from up to crashed
```

**Comment by NilsVollmer** [comment]
Es gibt noch ein anderes Problem: die worker laufen auf claradmin aber die vorlagen für die Mails liegen noch in clarat. Die manuelle Ausführung eines worker führt deshalb zu einem Fehler:
```console
irb(main):003:0> worker = ExpiringOffersWorker.new
=> #<ExpiringOffersWorker:0x007fed708d2880>
irb(main):004:0> worker.perform

OfferMailer#expiring_mail: processed outbound mail in 14.3ms
ActionView::MissingTemplate: Missing template offer_mailer/expiring_mail with "mailer". Searched in:
  * "offer_mailer"
```

**Comment by NilsVollmer** [comment]
Also es gab zwei Probleme: 
1. Sidekiq 3.5. (bzw. das enthaltene Celluloid 0.17.) scheint nicht kompatibel mit sidetiq zu sein und hat den oberen Fehler produziert. Deshalb ist in clarat_base jetzt sidekiq 3.4.2. fixiert was mit Celluloid 0.16. kommt und kompatibel ist.

siehe auch: https://github.com/tobiassvn/sidetiq/issues/140

2. Können einige Worker in claradmin nicht funktionieren, weil z.B. die Mailvorlagen noch in clarat liegen. Deshalb habe ich jetzt erst einmal die worker (inkl. procfile) wieder auf clarat aktiviert und auf claradmin deaktiviert.

Ergo läuft es jetzt hoffentlich wieder und wir müssen uns dann nur überlegen, wo dir worker ausgeführt werden sollen. Wenn das in claradmin passieren soll, müssen wir noch einige Dateien verschieben.
