### ISSUE TITLE
Show_in_app führt zu Application error

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#637]
Beispiel: http://claradmin.herokuapp.com/admin/offer/922

Problem: Preview funktioniert nicht und es folgt ein Application Error. Analyse der Logs zeigt, dass es an dem generierten Slug liegt, der Sonderzeichen enthält und deshalb einen URIError erzeugt.

```Console
2016-01-21T10:35:26.436736+00:00 app[web.1]: Started GET "/admin/offer/922/show_in_app" for 213.148.154.178 at 2016-01-21 10:35:26 +0000
2016-01-21T10:35:26.462460+00:00 app[web.1]: Completed 302 Found in 23ms (ActiveRecord: 1.4ms)
2016-01-21T10:35:26.526669+00:00 app[web.1]: Processing by OffersController#show as HTML
2016-01-21T10:35:26.526697+00:00 app[web.1]:   Parameters: {"id"=>"beratung-für-intersexuelle-und-transsexuelle"}
2016-01-21T10:35:26.530751+00:00 app[web.1]: Redirected to http://www.clarat.org/refugees/preview/angebote/beratung-für-intersexuelle-und-transsexuelle
2016-01-21T10:35:26.534333+00:00 app[web.1]: [2016-01-21 10:35:26] ERROR URI::InvalidURIError: URI must be ascii only "http://www.clarat.org/refugees/preview/angebote/beratung-f\u{fc}r-intersexuelle-und-transsexuelle"
2016-01-21T10:35:26.534335+00:00 app[web.1]: 	/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/uri/generic.rb:1100:in `rescue in merge'
2016-01-21T10:35:26.534336+00:00 app[web.1]: 	/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/uri/generic.rb:1097:in `merge'
2016-01-21T10:35:26.534337+00:00 app[web.1]: 	/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpresponse.rb:276:in `setup_header'
2016-01-21T10:35:26.534338+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:16:in `setup_header'
2016-01-21T10:35:26.534339+00:00 app[web.1]: 	/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpresponse.rb:206:in `send_response'
2016-01-21T10:35:26.534340+00:00 app[web.1]: 	/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:110:in `run'
2016-01-21T10:35:26.534341+00:00 app[web.1]: 	/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
2016-01-21T10:35:26.439562+00:00 app[web.1]: Processing by RailsAdmin::MainController#show_in_app as HTML
2016-01-21T10:35:26.439649+00:00 app[web.1]:   Parameters: {"model_name"=>"offer", "id"=>"922"}
2016-01-21T10:35:26.462052+00:00 app[web.1]: Redirected to http://claradmin.herokuapp.com/offers/beratung-f%C3%BCr-intersexuelle-und-transsexuelle
2016-01-21T10:35:26.524532+00:00 app[web.1]: Started GET "/offers/beratung-f%C3%BCr-intersexuelle-und-transsexuelle" for 213.148.154.178 at 2016-01-21 10:35:26 +0000
2016-01-21T10:35:26.531031+00:00 app[web.1]: Completed 302 Found in 4ms (ActiveRecord: 0.6ms)
```

Eigentlich sollten solche slugs nicht generiert werden (es gibt etliche, in denen korrekt aus für => fuer im slug wird) also scheint es da einen Bug zu geben.

Priorität je nachdem, wie oft das auftritt und dadurch die Researcher bei der Arbeit behindert. Aktuell wissen wir nur von diesem Angebot.

**Comment by KonstantinKo** [comment]
Kann den bug nicht nachvollziehen.

**Comment by KonstantinKo** [comment]
Konkretisiere: Kann den Bug nicht lokal reproduzieren. Gebe ich lokal dieselben Daten wie im gegebenen Beispiel ein, tritt der Bug nicht auf. Es fehlt also noch irgendeine Beobachtung, wann genau der Bug auftritt.

**Comment by KonstantinKo** [comment]
Closed bis mehr Infos verfügbar.
