### ISSUE TITLE
Probleme mit Umlauten in URLs

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#693]
Wenn man die URL http://awo-südost einer Organisation hinzufügt und sich dann im Frontend die Organisation anschauen will kommt in den Logs der folgende Fehler:

ActionView::Template::Error (URI must be ascii only "http://www.awo-s\u{fc}dost.de"):
    58:                       span.locality= location.city
    59:                   - if website
    60:                     br
    61:                     = link_to website.shorten_url + website.pdf_appendix,
    62:                       website.url, target: '_blank'
    63:
    64:                 /! http://microformats.org/wiki/adr end
  app/views/organizations/show.html.slim:61:in `block in _app_views_organizations_show_html_slim__4093613648829407651_70246924651380'
2016-02-17T15:32:21.134849+00:00 app[web.1]: app/views/organizations/show.html.slim:40:in `_app_views_organizations_show_html_slim__4093613648829407651_70246924651380'
2016-02-17T15:32:21.134849+00:00 app[web.1]:   app/controllers/previews_controller.rb:29:in `show'
2016-02-17T15:32:21.134851+00:00 app[web.1]:   app/controllers/previews_controller.rb:17:in `show_organization'

**Comment by KonstantinKo** [comment]
Als fix direkt auf develop umgesetzt.
