### ISSUE TITLE
Application Error auf claradmin-staging 

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#774]
Hatte gerade einen AppError mit einem 'alten' Bekannten (Unable to load application: TypeError: superclass must be a Class (Module given))

``` console
2016-04-19T09:24:51.675537+00:00 heroku[web.1]: State changed from crashed to starting
2016-04-19T09:25:02.435914+00:00 heroku[web.1]: Starting process with command `bundle exec puma -C config/puma.rb`
2016-04-19T09:25:04.430105+00:00 app[web.1]: [3] Puma starting in cluster mode...
2016-04-19T09:25:04.430172+00:00 app[web.1]: [3] * Version 3.1.0 (ruby 2.3.0-p0), codename: El Niño Winter Wonderland
2016-04-19T09:25:04.430181+00:00 app[web.1]: [3] * Min threads: 2, max threads: 2
2016-04-19T09:25:04.430187+00:00 app[web.1]: [3] * Environment: production
2016-04-19T09:25:04.430188+00:00 app[web.1]: [3] * Process workers: 2
2016-04-19T09:25:04.430188+00:00 app[web.1]: [3] * Preloading application
2016-04-19T09:25:07.406425+00:00 app[web.1]: /app/app/concepts/backend/index_table/pagination_cell/pagination_cell.rb:3:in `<module:IndexTable>': superclass must be a Class (Module given) (TypeError)
2016-04-19T09:25:07.406440+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
2016-04-19T09:25:07.406443+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
2016-04-19T09:25:07.406439+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
2016-04-19T09:25:07.406438+00:00 app[web.1]: 	from /app/app/concepts/backend/index_table/pagination_cell/pagination_cell.rb:2:in `<top (required)>'
2016-04-19T09:25:07.406138+00:00 app[web.1]: [3] ! Unable to load application: TypeError: superclass must be a Class (Module given)
2016-04-19T09:25:07.406463+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/trailblazer-rails-0.1.6/lib/trailblazer/rails/railtie.rb:16:in `glob'
2016-04-19T09:25:07.406464+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/trailblazer-rails-0.1.6/lib/trailblazer/rails/railtie.rb:16:in `autoload_cells'
2016-04-19T09:25:07.406447+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:233:in `require_dependency'
2016-04-19T09:25:07.406465+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/trailblazer-rails-0.1.6/lib/trailblazer/rails/railtie.rb:32:in `block (2 levels) in <class:Railtie>'
2016-04-19T09:25:07.406475+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:446:in `block in make_lambda'
2016-04-19T09:25:07.406476+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:192:in `block in simple'
2016-04-19T09:25:07.406477+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `block in call'
2016-04-19T09:25:07.406478+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `each'
2016-04-19T09:25:07.406443+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:360:in `require_or_load'
2016-04-19T09:25:07.406498+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
2016-04-19T09:25:07.406487+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
2016-04-19T09:25:07.406500+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
2016-04-19T09:25:07.406596+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
2016-04-19T09:25:07.406489+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
2016-04-19T09:25:07.406487+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `call'
2016-04-19T09:25:07.406440+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
2016-04-19T09:25:07.406600+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
2016-04-19T09:25:07.406599+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
2016-04-19T09:25:07.406602+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
2016-04-19T09:25:07.406602+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
2016-04-19T09:25:07.406449+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/trailblazer-rails-0.1.6/lib/trailblazer/rails/railtie.rb:17:in `block in autoload_cells'
2016-04-19T09:25:07.406598+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
2016-04-19T09:25:07.406604+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
2016-04-19T09:25:07.406603+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
2016-04-19T09:25:07.406600+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
2016-04-19T09:25:07.406446+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:317:in `depend_on'
2016-04-19T09:25:07.406466+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:446:in `instance_exec'
2016-04-19T09:25:07.406605+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
2016-04-19T09:25:07.406601+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
2016-04-19T09:25:07.406499+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
2016-04-19T09:25:07.406607+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
2016-04-19T09:25:07.406606+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
2016-04-19T09:25:07.406606+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
2016-04-19T09:25:07.406605+00:00 app[web.1]: 	from /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
2016-04-19T09:25:07.406613+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
2016-04-19T09:25:07.406608+00:00 app[web.1]: 	from /app/config/environment.rb:5:in `<top (required)>'
2016-04-19T09:25:07.406611+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
2016-04-19T09:25:07.406610+00:00 app[web.1]: 	from config.ru:3:in `block in <main>'
2016-04-19T09:25:07.406610+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
2016-04-19T09:25:07.406612+00:00 app[web.1]: 	from config.ru:in `<main>'
2016-04-19T09:25:07.406609+00:00 app[web.1]: 	from config.ru:3:in `require'
2016-04-19T09:25:07.406616+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/configuration.rb:245:in `app'
2016-04-19T09:25:07.406618+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/launcher.rb:173:in `run'
2016-04-19T09:25:07.406614+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
2016-04-19T09:25:07.406612+00:00 app[web.1]: 	from config.ru:in `new'
2016-04-19T09:25:07.406617+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/cluster.rb:362:in `run'
2016-04-19T09:25:07.406622+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/cli.rb:74:in `run'
2016-04-19T09:25:07.406624+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/bin/puma:23:in `<main>'
2016-04-19T09:25:07.406613+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
2016-04-19T09:25:07.406623+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/bin/puma:10:in `<top (required)>'
2016-04-19T09:25:07.406623+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/bin/puma:23:in `load'
2016-04-19T09:25:07.406615+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/configuration.rb:316:in `load_rackup'
2016-04-19T09:25:07.406616+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/runner.rb:119:in `load_and_bind'
```

Nach restart hat es allerdings wieder geklappt.

**Comment by NilsVollmer** [comment]
Update: der bekannt Fehler (TypeError: superclass must be a Class (Module given)) ist relativ nervig und kann anscheinend bei allen möglichen Kommandos (deploy, rails c, rake cache:clear etc.) auftreten.

Bevor das live geht, sollten wir den Fehler in den Griff bekommen.

**Comment by KonstantinKo** [comment]
hopefully fixed
